background {
    monitor =
    path = screenshot
    blur_passes = 2
}

label {
    monitor =
    text = cmd[update:1000] date +"%I:%M:%S %p"
    color = rgba(57, 255, 20, 0.95)
    font_size = 90
    font_family = DepartureMono Nerd Font Mono
    position = 0, 300
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %B %d, %Y"
    color = rgba(118, 255, 60, 0.80)
    font_size = 24
    font_family = DepartureMono Nerd Font Mono
    position = 0, 210
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 3
    dots_center = true
    position = 0, -50
    halign = center
    valign = center
    inner_color = rgba(10, 15, 10, 0.5)
    outer_color = rgba(57, 255, 20, 1)
    font_color = rgba(198, 245, 206, 1)
    dots_color = rgba(57, 255, 20, 1)
    check_color = rgba(0, 255, 200, 1)
    fail_color = rgba(255, 45, 85, 1)
}

label {
    monitor =
    text = cmd[update:1000] echo "Linux is love, Linux is life  "
    color = rgba(0, 229, 160, 0.85)
    font_size = 20
    font_family = DepartureMono Nerd Font Mono
    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor =
    text =  + X: leave Hyprland |  + Shift + P: shutdown |  + Shift + R: reboot
    color = rgba(47, 74, 53, 1)
    font_size = 14
    font_family = DepartureMono Nerd Font Mono
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:0] echo "Powered by Manjaro ($(lsb_release -rs))"
    color = rgba(0, 255, 200, 0.9)
    font_size = 14
    font_family = DepartureMono Nerd Font Mono
    position = 0, 50
    halign = center
    valign = bottom
}
